### ISSUE TITLE
Error because npm promote `ajv-keywords`

### ISSUE THREAD

**Issue by Val-istar-Guo** [ajv-validator/ajv-keywords#170]
Run `npm list ajv ajv-keywords` in my project:

```
├─┬ eslint@7.25.0
│ ├─┬ @eslint/eslintrc@0.4.0
│ │ └── ajv@6.12.6 
│ ├── ajv@6.12.6 
│ └─┬ table@6.6.0
│   └── ajv@8.2.0 
└─┬ mili@3.10.2
  ├── UNMET PEER DEPENDENCY ajv@8.2.0 
  ├── ajv-keywords@5.0.0 
  └─┬ npm@6.14.13
    └─┬ request@2.88.0
      └─┬ har-validator@5.1.5
        └── ajv@6.12.6 
```

My project don't depend on `ajv`, But the dependencies of my project depend on `ajv` and `ajv-keywords`. `ajv-keyword` was promote to `./node_modules/ajv-keyworkds` because it isn't conflict, but `ajv` not.....

However the actual installation effect is：

```
├── ajv-keywords@5.0.0 
├─┬ eslint@7.25.0
│ ├─┬ @eslint/eslintrc@0.4.0
│ │ └── ajv@6.12.6 
│ ├── ajv@6.12.6 
│ └─┬ table@6.6.0
│   └── ajv@8.2.0 
└─┬ mili@3.10.2
  ├── UNMET PEER DEPENDENCY ajv@8.2.0 
  
  └─┬ npm@6.14.13
    └─┬ request@2.88.0
      └─┬ har-validator@5.1.5
        └── ajv@6.12.6 
```

And `mili` Throw Error:

```
Cannot find module 'ajv/dist/compile/codegen'
Require stack:
- ....../node_modules/ajv-keywords/dist/definitions/typeof.js
- ....../node_modules/ajv-keywords/dist/keywords/typeof.js
```

`peerDependencies` is not easy to use。。。

**Comment by medikoo** [comment]
I can confirm, that any installation with npm v6 of project that has:
- dependency that depends on `ajv` v8, `ajv-keywords` v5
- `eslint` (which depends on `ajv` v6)

Is getting broken, because npm installs `ajv` v6 and `ajv-keywords` v5 top level

**Comment by Val-istar-Guo** [comment]
> I can confirm, that any installation with npm v6 of project that has:
> 
> * dependency that depends on `ajv` v8, `ajv-keywords` v5
> * `eslint` (which depends on `ajv` v6)
> 
> Is getting broken, because npm installs `ajv` v6 and `ajv-keywords` v5 top level

I understand the reason for the error, but there is no way to solve this problem elegantly.
I have to run `npm install ajv@8`  in my project.
Even if my project doesn't require ajv8 directly.

**Comment by medikoo** [comment]
> I understand the reason for the error, but there is no way to solve this problem elegantly.

This is a bug on the npm v6 side (see: https://github.com/npm/npm/issues/19877)  AFAIK it can be fixed simply by upgrading to npm v7 or later (default starting from Node.js v16). Otherwise, there's no reliable fix, assuming the current design of `ajv-keywords`

It could be worked around in `ajv-keywords` if similarly as `ajv-format` it'll drop peer dependency on AJV, so providing it with `ajv` instance would be good enough  (cc @epoberezkin ).

In [serverless](https://github.com/serverless/serverless/) we're considering hard-coding what we need from `ajv-keywords` (and it's just `regex`) into our package to workaround that until npm v6 is EOL

**Comment by Val-istar-Guo** [comment]
Thank you for your help. I guess my best solution is to wait for npm7 to be supported in my project.

**Comment by sag1v** [comment]
happens also on npm v9.8.1
